name: Manual Trigger with Multiple Jobs

on:
  workflow_dispatch:  

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Job 1
        run: echo "Executing Job 1"

  job2:
    name: Second Job
    runs-on: ubuntu-latest
    needs: job1  
    steps:
      - name: Run Job 2
        run: echo "Executing Job 2"

  job3:
    name: Third Job (Parallel)
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 3
        run: echo "Executing Job 3"

  job4:
    name: Dependent Job
    runs-on: ubuntu-latest
    needs: [job2, job3] 
    steps:
      - name: Run Job 4
        run: echo "Executing Job 4 after job2 and job3"
