name: Deploy Nginx, Tree, and MySQL on EC2

on:
  # push:
  #   branches:
  #     - main 
  workflow_dispatch:

jobs:
  install_nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Install Nginx
        env:
          HOST: ${{ secrets.EC2_PUBLIC_IP }}
          USER: ubuntu  
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          sudo apt update -y
          sudo apt install nginx -y
          echo "Nginx Installation Completed"
          EOF

  install_tree:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Install Tree
        env:
          HOST: ${{ secrets.EC2_PUBLIC_IP }}
          USER: ubuntu  
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          sudo apt install tree -y
          echo "Tree Installation Completed"
          EOF

  install_mysql:
    runs-on: ubuntu-latest
    needs: install_nginx  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Install MySQL
        env:
          HOST: ${{ secrets.EC2_PUBLIC_IP }}
          USER: ubuntu  
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          sudo apt install mysql-server -y
          sudo systemctl start mysql
          sudo systemctl enable mysql
          echo "MySQL Installation Completed"
          EOF

